### ISSUE TITLE
Expiration Date or Time to Update property  for Imported Items

### ISSUE THREAD

**Issue by Long-Man** [Montellese/xbmc#65]
Since content for streaming providers changes from time to time, it would be great to allow developers to return an "expire" or "update" timestamp for the content. If the "expire" is reached, content could be removed from database. When "update" is reached, Kodi should call a defined entrypoint to fetch updated data of the video entry.

**Comment by Long-Man** [comment]
@Montellese I have been thinking about these and wondering if it is necessary. Since synchronization is managed by the importer, and the fact that a change-set is accepted by Kodi. The importer should check the source and present the items to be added, removed and updated. It seems to me that it is possible to do that now.
On wake, the importer checks and present change-set and while online the importer monitors the source and present any changes.
Am correct in this reasoning?

**Comment by Montellese** [comment]
Yes in general a mediaimporter add-on can provide Kodi with a list of added / updated / removed items and Kodi will handle it from there.

In general I have no idea what's easier for plugins:
- provide a list of items and Kodi determines what has changed
- provide a list of changed items

I also don't know if we need to let users choose which parts of a plugin to import (e.g. only Youtube favourites).

We need a list of use cases to be able to determine the best approach.

**Comment by Long-Man** [comment]
Providing a list of changed items would be faster. And considering that there could be a number of addons, allowing them make the decisions will be a kind of faux parallel processing on startup.

I am not sure if you are aware, but a lot of these addons already have a export feature which allow the export of an item ie movie, tv show, season. Didn't try an episode or music video. I know it is present in Netflix and Amazon Prime as I used those two. Not sure of the others.

Maybe we could ask the developers to put in an event announcing the export which could be used to add an item to the library instead of generating or in addition to the stream file. What would be needed in such an event?

**Comment by flubshi** [comment]
> In general I have no idea what's easier for plugins:
> 
> * provide a list of items and Kodi determines what has changed
> * provide a list of changed items

This depends on the streaming provider API, an addon talks to. In case of my plugin, it is easier to return a list of all library items and let Kodi handle the diff. But there might other plugins/addons that are able to update entries or provide a diff. Especially for large collections a full sync might be impossible.

> I also don't know if we need to let users choose which parts of a plugin to import (e.g. only Youtube favourites).

I think the developers should decide what an addon adds to library. Kodi just needs to provide an interface to retrieve the items. In case of youtube, Addon developers could add an options to plugin settings, to give the user a choice what to import (e.g. just favorites).

**Comment by flubshi** [comment]
I started implementing a very basic media importer for my plugin. I am very happy with your current interface and I currently do no longer see a need for an `expiration date to update property`.

Thanks for creating documentation, it helped me!

**Comment by Montellese** [comment]
> I started implementing a very basic media importer for my plugin. I am very happy with your current interface and I currently do no longer see a need for an `expiration date to update property`.
> 
> Thanks for creating documentation, it helped me!

That sounds great. Let me know if you have any improvement ideas and I'd also be interested to see your implementation once it's available.

**Comment by flubshi** [comment]
Implementation is still WIP, I am still experimenting. A very basic attempt [can be found here](https://github.com/flubshi/plugin.video.waipu.tv/tree/matrix_media_import)

**Comment by Montellese** [comment]
> Implementation is still WIP, I am still experimenting. A very basic attempt [can be found here](https://github.com/flubshi/plugin.video.waipu.tv/tree/matrix_media_import)

That looks very promising. A few comments:
* Do you think it makes sense to add some kind of flag to automatically create a provider so that you don't have to provide an `observer` or implement the `discoverprovider` or `lookupprovider` actions / endpoints? The only downside is that the user will only get a single provider for such add-ons. I'm not sure if that is an issue though.
* Concerning the `MediaProvider` you create I would suggest to use the `plugin://` path as the base URL instead of `127.0.0.1`.
* Are username and password already configured for the add-on? If so would it make sense to just access those for importing instead of having to re-define them in the `providersettings.xml`?

**Comment by flubshi** [comment]
All good points that came up for me as well:

> * Do you think it makes sense to add some kind of flag to automatically create a provider so that you don't have to provide an `observer` or implement the `discoverprovider` or `lookupprovider` actions / endpoints? The only downside is that the user will only get a single provider for such add-ons. I'm not sure if that is an issue though.

Some interface methods feel like stubs for my use case. For multiple addons it might be sufficient to to add only a single provider/account, e.g. if the content is the same. At the moment, multiple 'normal' addons provide support for a single account. So, in my option it makes sense provide such a flag :)

> * Concerning the `MediaProvider` you create I would suggest to use the `plugin://` path as the base URL instead of `127.0.0.1`.

Done - thanks. What is it used for?


> * Are username and password already configured for the add-on? If so would it make sense to just access those for importing instead of having to re-define them in the `providersettings.xml`?

During my implementation I tried to access the existing plugin settings and read the credentials from there. But it did not work. Of course it does not make sense to enter the credentials twice for a single addon. Is it possible to access the 'normal' plugin settings from within the plugin?

**Comment by Montellese** [comment]
> > * Do you think it makes sense to add some kind of flag to automatically create a provider so that you don't have to provide an `observer` or implement the `discoverprovider` or `lookupprovider` actions / endpoints? The only downside is that the user will only get a single provider for such add-ons. I'm not sure if that is an issue though.
> 
> Some interface methods feel like stubs for my use case. For multiple addons it might be sufficient to to add only a single provider/account, e.g. if the content is the same. At the moment, multiple 'normal' addons provide support for a single account. So, in my option it makes sense provide such a flag :)

OK I'll try to come up with something.

> > * Concerning the `MediaProvider` you create I would suggest to use the `plugin://` path as the base URL instead of `127.0.0.1`.
> 
> Done - thanks. What is it used for?

UPnP importer and mediaimporter.emby / plex use it to store the URL of the server to connect to. Originally this was the "unique identifier" but I've added a separate one since then. So it's not mandatory anymore but IMO it's good practice to put a path that Kodi can "understand".

> > * Are username and password already configured for the add-on? If so would it make sense to just access those for importing instead of having to re-define them in the `providersettings.xml`?
> 
> During my implementation I tried to access the existing plugin settings and read the credentials from there. But it did not work. Of course it does not make sense to enter the credentials twice for a single addon. Is it possible to access the 'normal' plugin settings from within the plugin?

Obviously I never tested that because mediaimporter.emby / plex don't have add-on settings. I'd expect it to work so I'll take a look.

**Comment by Montellese** [comment]
> > During my implementation I tried to access the existing plugin settings and read the credentials from there. But it did not work. Of course it does not make sense to enter the credentials twice for a single addon. Is it possible to access the 'normal' plugin settings from within the plugin?
> 
> Obviously I never tested that because mediaimporter.emby / plex don't have add-on settings. I'd expect it to work so I'll take a look.

I have given this a try and if you use one of the following codes you should be able to access the add-ons settings:
```
addon = xbmcaddon.Addon()
username = addon.getSetting("username")
password = addon.getSetting("password")
provider = addon.getSettingInt("provider_select")
```
or
```
addon = xbmcaddon.Addon()
addonSettings = addon.getSettings()
username = addonSettings.getString("username")
password = addonSettings.getString("password")
provider = addonSettings.getInt("provider_select")
```
Using `xbmcplugin.getSetting()` doesn't work because the script isn't called as a plugin script.

With this you should be able to completely drop `providersettings.xml`.

**Comment by Long-Man** [comment]
I have been thinking about how I use the *Export Feature* of the Netflix and Amazon Prime addons and I suspect that it may not be de-similar to how many others use it.

I have a few series that I watch from each source;
   > Lost in Space, Goliath, The Expanse, Ozarks, Altered Carbon, Money Heist, Tom Clancy's Jack Ryan among others.  

I usually just export the strm files and scan them into the library. I check for the date of the next release and just export the new season. I take a similar approach to movies, if i see one I am interested in I export it.  

I do this for two main reasons, firstly to have the series in my in progress so that I wouldn't have to dig into the addon each time I sit to continue the series. And secondly to propagate to multiple devices. For this I use Emby, but I am sure it would be the same with UPnP Importing from central Kodi instance.

I was browsing this morning and noticed that each addon has a list, ***My List*** for Netflix and ***Watched List*** for Amazon, which allows one to select their desired media items. Would it make sense to use this list, or one created for the purpose to act as the ***Imports*** from the addon. In that way the User would browse the addon and add to that list any media item that they want to export and MediaImport would interact with that list. Each time an item is added, removed or updated an event is fired, similar in outcome, to the websocket events from Emby, to announce the event which MediaImport would respond to. Addons authors would implement could add it to the current addons.

I must admit I am not sure about the technical details of the events so it may not be as easy as I am thinking.

What are you thoughts?

**Comment by Montellese** [comment]
> Some interface methods feel like stubs for my use case. For multiple addons it might be sufficient to to add only a single provider/account, e.g. if the content is the same. At the moment, multiple 'normal' addons provide support for a single account. So, in my option it makes sense provide such a flag :)

I've played around a bit and came up with the following extension point definition for your use case:
```xml
<extension point="kodi.mediaimporter" library="importer.py">
  <automaticallyaddasprovider>true</automaticallyaddasprovider>
  <supportedmediatypes>movies</supportedmediatypes>
  <providersettings prepare="false">providersettings.xml</providersettings>
</extension>
```
which results in
* `<automaticallyaddasprovider>` will automatically add a new provider when the add-on is installed / enabled. The provider uses the ID, name and icon from the add-on and the supported media types from `<supportedmediatypes>`. That way you can completely drop the `discoverprovider` and `lookupprovider` actions / endpoints from `importer.py`.
* `<providersettings prepare="false">providersettings.xml</providersettings>` indicates that settings definitions should be loaded from `providersettings.xml` but that the `loadprovidersettings` action / endpoint doesn't need to be executed. That way you can completely drop it from `importer.py`. The same goes for `loadimportsettings`.

Obviously in your case you don't need the `providersettings.xml` at all because you can read the settings from the add-ons settings as mentioned above.

What do you think?

I'm also thinking about making `canimport` optional. Right now it is only used for the UPnP media importer so maybe there's another way to solve this or make it optional.

Last but not least another hint for your media import integration: the idea behind the `isproviderready` and `isimportready` actions / endpoints is that you make sure that the user has configured everything properly. In your case that would mean that you test whether the username and password actually work. If they don't work (missing, typo, outdated) there's no use in trying to import media items because it will fail.

**Comment by Montellese** [comment]
> I do this for two main reasons, firstly to have the series in my in progress so that I wouldn't have to dig into the addon each time I sit to continue the series.

This would also work with the current approach or do you see any potential issues?

And secondly to propagate to multiple devices. For this I use Emby, but I am sure it would be the same with UPnP Importing from central Kodi instance.

Do you export the items as strm and add them to Emby?
This would currently not work with UPnP media importing because a Kodi installation can only "export" media items that haven't been imported from another provider. Because otherwise in a mesh setup (multiple Kodi installations importing from each other) you would end up with lots of duplicates.

> I was browsing this morning and noticed that each addon has a list, _**My List**_ for Netflix and _**Watched List**_ for Amazon, which allows one to select their desired media items. Would it make sense to use this list, or one created for the purpose to act as the _**Imports**_ from the addon. In that way the User would browse the addon and add to that list any media item that they want to export and MediaImport would interact with that list. Each time an item is added, removed or updated an event is fired, similar in outcome, to the websocket events from Emby, to announce the event which MediaImport would respond to. Addons authors would implement could add it to the current addons.

That was / is one of my open questions concerning who decides / controls what is imported. Should the user be able to pick single items or folders which will be imported? Or does the add-on specify that only items in a specific list (e.g. YouTube's _Favourites_ or Netflix's _My List_) and the user has to use the add-on to add the items to that list?

> I must admit I am not sure about the technical details of the events so it may not be as easy as I am thinking.

There wouldn't be any need for any special event. The add-on could simply call the `xbmcmediaimport.changeItems()` API method to add / update remove the items whenever they change in the add-on.

**Comment by Long-Man** [comment]
> Do you export the items as strm and add them to Emby?  

Yes. It was my hack circa 2014 for Youtube which I later applied to Netflix and Prime when they became available to Kodi.

> ...multiple Kodi installations importing from each other you would end up with lots of duplicates.
  
That's true. I had forgotten that

>Should the user be able to pick single items or folders which will be imported?  

If there no limitation of the established approaches, I think it is more advantageous to use them and extend if necessary. Change is stressful and many people avoid it. Keeping the status quo lowers the bar to entry.

Right now Amazon allows both Individual Seasons and Movies, while Netflix does Individual Shows, Seasons and Movies. Even so the will always want to select individual items. I think we should encourage, if not require, the developer to send that item to a list and MediaImport only interact with that list. You could even allow multiple lists that are treat similarly to libraries from Emby or Plex.

**Comment by flubshi** [comment]
> Last but not least another hint for your media import integration: the idea behind the `isproviderready` and `isimportready` actions / endpoints is that you make sure that the user has configured everything properly.

Thanks. Did not yet implement it due to laziness :P I assume `isimportready` is only called when `isproviderready` succeeded? Thus, I do not need to implement an account check for both, but only for `isproviderready`?
I added a commit that improves my implementation of `isproviderready` :)



> I've played around a bit and came up with the following extension point definition for your use case:

I like this approach. But wouldn't `<supportedmediatypes>movies</supportedmediatypes>` imply that `<automaticallyaddasprovider>true</automaticallyaddasprovider>` is set? Thus, there is no need for `automaticallyaddasprovider`.
If `supportedmediatypes` is set, it would automatically add a provider for us, otherwise the plugin is responsible for implementing the callback.



>  \<providersettings prepare="false">providersettings.xml</providersettings

I think this is a suitable solution. :)

**Comment by Montellese** [comment]
> I assume `isimportready` is only called when `isproviderready` succeeded? Thus, I do not need to implement an account check for both, but only for `isproviderready`?

That's correct.

> I like this approach. But wouldn't `<supportedmediatypes>movies</supportedmediatypes>` imply that `<automaticallyaddasprovider>true</automaticallyaddasprovider>` is set? Thus, there is no need for `automaticallyaddasprovider`.
> If `supportedmediatypes` is set, it would automatically add a provider for us, otherwise the plugin is responsible for implementing the callback.

Yes but I don't like implicit definitions like this. But maybe I should change it to something like
```xml
<automaticallyaddasprovider>
  <supportedmediatypes>movies</supportedmediatypes>
</automaticallyaddasprovider>
```
That way you cannot use `<supportedmediatypes>` without <automaticallyaddasprovider>` and it's more obvious that they belong together. What do you think?

**Comment by Montellese** [comment]
> Right now Amazon allows both Individual Seasons and Movies, while Netflix does Individual Shows, Seasons and Movies. Even so the will always want to select individual items. I think we should encourage, if not require, the developer to send that item to a list and MediaImport only interact with that list. You could even allow multiple lists that are treat similarly to libraries from Emby or Plex.

Well I'm kinda torn: on the one hand IMO the media importer implementation doesn't and shouldn't have to know about the plugin specific list(s). The downside of that is that there is no unified experience for users. In the Netflix plugin you have to use action X to get an item into the proper list and in Amazon Prize it's action Y and so on. But on the other hand if we try to unify it we also have to cover all special cases like updating the imported items, decide when to remove them and so on. That's why I'm hesitant about introducing a unified approach...

**Comment by Long-Man** [comment]
It might be difficult to avoid lists with the plugins though. Servers like Emby and Plex already have a ***list*** of what has been exported in the form of their libraries. Unless one exports all items from an addon, there is no such list for tracking.

> In the Netflix plugin you have to use action X to get an item into the proper list and in Amazon Prize it's action Y and so on.  

That's true. However in these cases, the user is already familiar with these differing methods and would have to learn a new method in some cases for a unified approach

**Comment by flubshi** [comment]
> That way you cannot use `<supportedmediatypes>` without ` and it's more obvious that they belong together. What do you think?

I think this is a better solution :)

**Comment by Montellese** [comment]
> It might be difficult to avoid lists with the plugins though. Servers like Emby and Plex already have a _**list**_ of what has been exported in the form of their libraries. Unless one exports all items from an addon, there is no such list for tracking.
> 
> > In the Netflix plugin you have to use action X to get an item into the proper list and in Amazon Prize it's action Y and so on.
> 
> That's true. However in these cases, the user is already familiar with these differing methods and would have to learn a new method in some cases for a unified approach

I think for now we have too little input / feedback from users and plugin developers. I'll probably stick to the currently available API and then we can still extend it or create a separate media importer implementation if it turns out that there's a need for it.
If we try to come up with the best solution now without knowing all the facts and details we are bound to get something wrong somewhere which will be much harder to fix than introducing a well thought through approach at a later point in time.

**Comment by Long-Man** [comment]
Make Sense.

**Comment by flubshi** [comment]
> Yes but I don't like implicit definitions like this. But maybe I should change it to something like
> 
> ```xml
> <automaticallyaddasprovider>
>   <supportedmediatypes>movies</supportedmediatypes>
> </automaticallyaddasprovider>
> ```

Is this already possible in `media_import_rebase_20200411`? I cannot find the commit (tbh: I do not understand the commit order :P ). I think, for your previous suggestion I saw a commit in the outdated branch.

**Comment by Montellese** [comment]
> Is this already possible in `media_import_rebase_20200411`? I cannot find the commit (tbh: I do not understand the commit order :P ). I think, for your previous suggestion I saw a commit in the outdated branch.

Yes it is. Test builds are being built by Jenkins right now and I'm going to publish them in the forums tomorrow.

To keep the number of commits "small" I usually squash new commits / fixes into the commits where I introduced the functionality. That's why the commit was there in my previous feature branch but not anymore in `media_import_rebase_20200411`.

You can now also use `<providersettings prepare="false">` if you don't want to implement the `loadprovidersettings` action. But since you will most likely not need a `providersettings.xml` at all you can drop it (and `loadimportsettings`) completely. So you should be able to get rid of
* `discoverprovider`
* `lookupprovider`
* `loadprovidersettings`
* `loadimportsettings`

**Comment by flubshi** [comment]
Thanks a lot! I applied your suggestions to my addon and implemented import of tv shows. My python code looks still horrible, but it works. I need to improve it soon...

I will provide more feedback if I notice something. But in general, your mediaimporter approach looks pretty good and is a much better solution than the .strm-export some video plugins use. In the long term this should definitively part of Kodi. Is there something we/I can help on?

**Comment by Montellese** [comment]
@flubshi great that you get along with the existing API so well. It's good to know that somebody other than myself understands how to use it ;-)

For now the main help I need is in testing because from experience testing your own stuff only ever covers around 25% of the special / corner cases.

**Comment by Long-Man** [comment]
@flubshi, I see where you encouraged the developers of the Disney+ addon to add a mediaimporter extention point to the addon and they were not receptive. Would you consider submitting a PR for one the addons? Thinking here of Disney+, Netflix, Youtube or Amazon Prime. Getting the feature in any of them would surely raise the project's profile. 

What are your thoughts?
Cheers,
LongMan

**Comment by Long-Man** [comment]
BTW for Youtube i am thining https://www.youtube.com/movies

**Comment by Montellese** [comment]
It would be great if we could "hack" media importing into one of the popular content add-ons to showcase its potential and what the user gains. But I wouldn't expect the devs of those add-ons to just jump at the idea and get to work on it.

**Comment by flubshi** [comment]
Sure, but testing is always hard without credentials. Today I got an Disney+ account (haven't checked it yet). Maybe I can start with that one. But it might take some time, because my time is limited the next weeks.
